name: Continuous integration
on: [push, pull_request]

jobs:
  spec:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: wasd
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Install mysql client
        run: |
          sudo apt-get -yqq install mysql-client
