name: Continuous integration
on: [push, pull_request]

jobs:
  spec:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7.29
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
        ports:
          - 3306/tcp

    steps:
      - uses: actions/checkout@v2

      - name: Install mysql client
        run: |
          sudo apt-get -yqq install mysql-client
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
