name: Continuous integration
on: [push, pull_request]

jobs:
  spec:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7.29
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: wasd
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
